worker_processes 5;
daemon off;

events {
    worker_connections 4096;
}

http {
    include $!{nginx}/conf/mime.types;

    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stdout;

    sendfile on;

    server {
        listen ${PORT};
        listen [::]:${PORT};

        server_name localhost;

        root /app/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include $!{nginx}/conf/fastcgi_params;
            include $!{nginx}/conf/fastcgi.conf;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}