<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-bold uppercase tracking-[0.2em] text-emerald-600">Paramètres</p><h2 class="mt-1 text-2xl font-black text-slate-900">Ajouter un utilisateur</h2><p class="mt-1 text-sm text-slate-500">Le compte sera rattaché à votre église existante.</p></div></x-slot>

    <div class="mx-auto max-w-2xl px-4 py-8 sm:px-6 lg:px-8"><div class="card-surface p-6 sm:p-8"><form method="POST" action="{{ route('settings.users.store') }}" class="space-y-5">@csrf
        <div><label for="name" class="mb-2 block text-sm font-bold text-slate-700">Nom complet</label><input id="name" name="name" value="{{ old('name') }}" class="block w-full rounded-lg border border-slate-300 px-3 py-2.5" required>@error('name')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="email" class="mb-2 block text-sm font-bold text-slate-700">Adresse email</label><input id="email" name="email" type="email" value="{{ old('email') }}" class="block w-full rounded-lg border border-slate-300 px-3 py-2.5" required>@error('email')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="role" class="mb-2 block text-sm font-bold text-slate-700">Rôle dans l’église</label><select id="role" name="role" class="block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5" required><option value="member" @selected(old('role') === 'member')>Membre équipe</option><option value="manager" @selected(old('role') === 'manager')>Responsable</option><option value="admin" @selected(old('role') === 'admin')>Administrateur</option></select>@error('role')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="password" class="mb-2 block text-sm font-bold text-slate-700">Mot de passe provisoire</label><input id="password" name="password" type="password" class="block w-full rounded-lg border border-slate-300 px-3 py-2.5" required>@error('password')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div><div><label for="password_confirmation" class="mb-2 block text-sm font-bold text-slate-700">Confirmer le mot de passe</label><input id="password_confirmation" name="password_confirmation" type="password" class="block w-full rounded-lg border border-slate-300 px-3 py-2.5" required></div></div>
        <div class="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-800">Partagez le mot de passe provisoire avec l’utilisateur par un canal privé. Il pourra ensuite utiliser la récupération de mot de passe.</div>
        <div class="flex flex-col-reverse justify-end gap-3 border-t border-slate-200 pt-6 sm:flex-row"><a href="{{ route('settings.users.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-bold text-slate-700">Annuler</a><button class="rounded-lg bg-[#123c35] px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-900">Ajouter à l’église</button></div>
    </form></div></div>
</x-app-layout>
